import type { InsertAccount } from "@shared/schema";

export interface DefaultAccountTemplate {
  code: string;
  nameEn: string;
  nameAr: string;
  description: string;
  type: "asset" | "liability" | "equity" | "income" | "expense";
  subType: string | null;
  isVatAccount: boolean;
  vatType: "input" | "output" | "zero_rated" | "exempt" | null;
  isSystemAccount: boolean;
}

export const defaultChartOfAccounts: DefaultAccountTemplate[] = [
  // ===========================
  // ASSETS - Current Assets (1000-1099)
  // ===========================
  {
    code: "1010",
    nameEn: "Cash on Hand",
    nameAr: "النقد في الصندوق",
    description: "Physical cash held at business premises",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "1020",
    nameEn: "Bank Accounts",
    nameAr: "الحسابات البنكية",
    description: "Funds held in business bank accounts",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "1025",
    nameEn: "Payment Gateway Clearing",
    nameAr: "حساب تسوية بوابة الدفع",
    description: "Card payments collected online and not yet paid out to the bank",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "1030",
    nameEn: "Petty Cash",
    nameAr: "النثرية",
    description: "Small cash fund for minor expenses",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "1040",
    nameEn: "Accounts Receivable",
    nameAr: "الذمم المدينة",
    description: "Amounts owed by customers for goods/services",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "1050",
    nameEn: "VAT Receivable (Input VAT)",
    nameAr: "ضريبة القيمة المضافة المستردة",
    description: "VAT paid on purchases, recoverable from FTA",
    type: "asset",
    subType: "current_asset",
    isVatAccount: true,
    vatType: "input",
    isSystemAccount: true,
  },
  {
    code: "1060",
    nameEn: "Prepaid Expenses",
    nameAr: "المصروفات المدفوعة مقدماً",
    description: "Expenses paid in advance (rent, insurance, etc.)",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "1070",
    nameEn: "Inventory",
    nameAr: "المخزون",
    description: "Goods held for sale or production",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },

  {
    code: "1080",
    nameEn: "Employee Loans",
    nameAr: "قروض الموظفين",
    description: "Loans and salary advances to employees, recovered through payroll deductions",
    type: "asset",
    subType: "current_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },

  // ===========================
  // ASSETS - Fixed Assets (1200-1299)
  // ===========================
  {
    code: "1210",
    nameEn: "Office Equipment",
    nameAr: "معدات المكتب",
    description: "Office machines, printers, and equipment",
    type: "asset",
    subType: "fixed_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "1220",
    nameEn: "Furniture & Fixtures",
    nameAr: "الأثاث والتركيبات",
    description: "Office furniture, desks, chairs, shelving",
    type: "asset",
    subType: "fixed_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "1230",
    nameEn: "Computers & Software",
    nameAr: "الحواسيب والبرمجيات",
    description: "Computer hardware and capitalized software",
    type: "asset",
    subType: "fixed_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "1240",
    nameEn: "Accumulated Depreciation",
    nameAr: "الاستهلاك المتراكم",
    description: "Total depreciation of fixed assets",
    type: "asset",
    subType: "fixed_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "1290",
    nameEn: "Fixed Assets at Cost",
    nameAr: "الأصول الثابتة بالتكلفة",
    description: "Aggregate fixed asset cost account used for capitalization and disposal entries",
    type: "asset",
    subType: "fixed_asset",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },

  // ===========================
  // LIABILITIES - Current Liabilities (2000-2099)
  // ===========================
  {
    code: "2010",
    nameEn: "Accounts Payable",
    nameAr: "الذمم الدائنة",
    description: "Amounts owed to suppliers and vendors",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "2015",
    nameEn: "Goods Received Not Invoiced",
    nameAr: "بضاعة مستلمة لم تتم فوترتها",
    description: "Stock received (purchase movements) before the supplier bill is booked; code the vendor bill to this account to clear it",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "2020",
    nameEn: "VAT Payable (Output VAT)",
    nameAr: "ضريبة القيمة المضافة المستحقة",
    description: "VAT collected on sales, payable to FTA",
    type: "liability",
    subType: "current_liability",
    isVatAccount: true,
    vatType: "output",
    isSystemAccount: true,
  },
  {
    code: "2025",
    nameEn: "FTA VAT Control Account",
    nameAr: "حساب مراقبة ضريبة القيمة المضافة - الهيئة الاتحادية للضرائب",
    description: "Net VAT payable/receivable to Federal Tax Authority",
    type: "liability",
    subType: "current_liability",
    isVatAccount: true,
    vatType: "output",
    isSystemAccount: true,
  },
  {
    code: "2030",
    nameEn: "Salaries Payable",
    nameAr: "الرواتب المستحقة",
    description: "Unpaid employee wages and salaries",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "2032",
    nameEn: "Pension Payable - GPSSA",
    nameAr: "المعاش المستحق - الهيئة العامة للمعاشات",
    description: "Employee and employer pension contributions due to GPSSA",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "2034",
    nameEn: "Payroll Deductions Payable",
    nameAr: "استقطاعات الرواتب المستحقة",
    description: "Payroll deductions pending settlement",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "2036",
    nameEn: "End-of-Service Gratuity Provision",
    nameAr: "مخصص مكافأة نهاية الخدمة",
    description: "Accrued end-of-service gratuity liability",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "2037",
    nameEn: "Leave Pay Provision",
    nameAr: "مخصص أجور الإجازات",
    description: "Accrued annual leave pay owed to employees for leave earned and not yet taken",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "2040",
    nameEn: "Accrued Expenses",
    nameAr: "المصروفات المستحقة",
    description: "Expenses incurred but not yet paid",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "2045",
    nameEn: "Employee Reimbursements Payable",
    nameAr: "مستحقات الموظفين",
    description: "Amounts owed to employees for approved out-of-pocket expense claims",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "2050",
    nameEn: "Customer Credit",
    nameAr: "رصيد دائن للعملاء",
    description: "Payments received above what the customer owed (overpayments), refundable from the customer's page",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "2055",
    nameEn: "Customer Advances",
    nameAr: "دفعات العملاء المقدمة",
    description: "Advance tax invoices and deposits received before the supply, until applied or refunded",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "2060",
    nameEn: "Corporate Tax Payable",
    nameAr: "ضريبة الشركات المستحقة",
    description: "UAE corporate tax accrued on a filed return and not yet paid to the FTA",
    type: "liability",
    subType: "current_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },

  // ===========================
  // LIABILITIES - Long-term Liabilities (2200-2299)
  // ===========================
  {
    code: "2210",
    nameEn: "Loan Payable",
    nameAr: "القروض المستحقة",
    description: "Long-term bank loans and financing",
    type: "liability",
    subType: "long_term_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "2220",
    nameEn: "Lease Liabilities",
    nameAr: "التزامات الإيجار",
    description: "Operating and finance lease obligations",
    type: "liability",
    subType: "long_term_liability",
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },

  // ===========================
  // EQUITY (3000-3099)
  // ===========================
  {
    code: "3010",
    nameEn: "Owner's Capital / Share Capital",
    nameAr: "رأس مال المالك / رأس المال",
    description: "Initial and additional owner investments",
    type: "equity",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "3020",
    nameEn: "Retained Earnings",
    nameAr: "الأرباح المحتجزة",
    description: "Accumulated profits not distributed to owners",
    type: "equity",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "3030",
    nameEn: "Dividends / Owner Drawings",
    nameAr: "توزيعات الأرباح / سحوبات المالك",
    description: "Distributions to owners/shareholders",
    type: "equity",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },

  // ===========================
  // INCOME / REVENUE (4000-4099)
  // ===========================
  {
    code: "4010",
    nameEn: "Product Sales",
    nameAr: "مبيعات المنتجات",
    description: "Revenue from sale of goods",
    type: "income",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "4020",
    nameEn: "Service Revenue",
    nameAr: "إيرادات الخدمات",
    description: "Revenue from services rendered",
    type: "income",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "4030",
    nameEn: "Other Income",
    nameAr: "إيرادات أخرى",
    description: "Miscellaneous non-operating income",
    type: "income",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "4035",
    nameEn: "Shipping Income",
    nameAr: "إيرادات الشحن",
    description: "Delivery and shipping charged to customers",
    type: "income",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "4040",
    nameEn: "Interest Income",
    nameAr: "إيرادات الفوائد",
    description: "Interest earned on deposits and investments",
    type: "income",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "4050",
    nameEn: "Discounts Given",
    nameAr: "الخصومات الممنوحة",
    description: "Sales discounts and allowances (contra-revenue)",
    type: "income",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "4060",
    nameEn: "Zero-Rated Sales",
    nameAr: "مبيعات بنسبة صفر",
    description: "Exports and designated zero-rated supplies per FTA",
    type: "income",
    subType: null,
    isVatAccount: true,
    vatType: "zero_rated",
    isSystemAccount: false,
  },
  {
    code: "4070",
    nameEn: "Exempt Sales",
    nameAr: "مبيعات معفاة",
    description: "VAT-exempt supplies (financial services, residential property)",
    type: "income",
    subType: null,
    isVatAccount: true,
    vatType: "exempt",
    isSystemAccount: false,
  },
  {
    code: "4080",
    nameEn: "Gain on Asset Disposal",
    nameAr: "ربح من بيع الأصول",
    description: "Gain recognized on disposal of fixed assets above net book value",
    type: "income",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "4090",
    nameEn: "Foreign Exchange Gain",
    nameAr: "أرباح صرف العملات الأجنبية",
    description: "Realised and unrealised gains on foreign-currency balances",
    type: "income",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },

  // ===========================
  // EXPENSES (5000-5199)
  // ===========================
  {
    code: "5000",
    nameEn: "General Expenses",
    nameAr: "مصروفات عامة",
    description: "Uncategorised expenses — default for posted VAT purchase bills",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5010",
    nameEn: "Rent Expense",
    nameAr: "مصروف الإيجار",
    description: "Office and premises rental costs",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5020",
    nameEn: "Salaries & Wages",
    nameAr: "الرواتب والأجور",
    description: "Employee compensation and benefits",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "5025",
    nameEn: "Pension Expense (Employer)",
    nameAr: "مصروف المعاش (صاحب العمل)",
    description: "Employer share of GPSSA and GCC pension contributions",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "5028",
    nameEn: "End-of-Service Gratuity Expense",
    nameAr: "مصروف مكافأة نهاية الخدمة",
    description: "Periodic accrual of UAE end-of-service gratuity liability",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "5029",
    nameEn: "Leave Pay Expense",
    nameAr: "مصروف أجور الإجازات",
    description: "Periodic accrual of annual leave pay earned and not yet taken",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "5030",
    nameEn: "Utilities",
    nameAr: "المرافق",
    description: "Electricity, water, and gas expenses",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5040",
    nameEn: "Telephone & Internet",
    nameAr: "الهاتف والإنترنت",
    description: "Communication and connectivity costs",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5050",
    nameEn: "Office Supplies",
    nameAr: "اللوازم المكتبية",
    description: "Stationery, consumables, and small office items",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5060",
    nameEn: "Marketing & Advertising",
    nameAr: "التسويق والإعلان",
    description: "Promotional and advertising expenses",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5070",
    nameEn: "Professional Services",
    nameAr: "الخدمات المهنية",
    description: "Legal, accounting, and consulting fees",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5080",
    nameEn: "Software Subscriptions",
    nameAr: "اشتراكات البرمجيات",
    description: "SaaS and software licensing costs",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5090",
    nameEn: "Travel & Meals",
    nameAr: "السفر والوجبات",
    description: "Business travel and entertainment expenses",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5100",
    nameEn: "Depreciation Expense",
    nameAr: "مصروف الاستهلاك",
    description: "Periodic depreciation of fixed assets",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "5110",
    nameEn: "Bank Charges & Fees",
    nameAr: "الرسوم والعمولات البنكية",
    description: "Bank service charges and transaction fees",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5120",
    nameEn: "Bad Debt Expense",
    nameAr: "مصروف الديون المعدومة",
    description: "Uncollectible accounts receivable written off",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: false,
  },
  {
    code: "5130",
    nameEn: "Loss on Asset Disposal",
    nameAr: "خسارة من بيع الأصول",
    description: "Loss recognized on disposal of fixed assets below net book value",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "5140",
    nameEn: "Foreign Exchange Loss",
    nameAr: "خسائر صرف العملات الأجنبية",
    description: "Realised and unrealised losses on foreign-currency balances",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "5150",
    nameEn: "Corporate Tax Expense",
    nameAr: "مصروف ضريبة الشركات",
    description: "UAE corporate tax on profits, accrued when the return is filed",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "5160",
    nameEn: "Irrecoverable VAT Expense",
    nameAr: "مصروف ضريبة القيمة المضافة غير القابلة للاسترداد",
    description: "Input VAT the VAT return does not recover (partial exemption, blocked tax) plus VAT rounding, expensed when the return is filed",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "5165",
    nameEn: "VAT Adjustments",
    nameAr: "تسويات ضريبة القيمة المضافة",
    description: "Difference posted when a VAT return declares MORE tax than the ledger supports (a manual edit with a written reason), kept apart from irrecoverable VAT",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "5200",
    nameEn: "Cost of Goods Sold",
    nameAr: "تكلفة البضاعة المباعة",
    description: "Weighted-average cost of inventory sold, posted when an invoice is issued",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
  {
    code: "5210",
    nameEn: "Inventory Adjustments",
    nameAr: "تسويات المخزون",
    description: "Stock-take corrections: stock found or lost (adjustment movements) valued at cost",
    type: "expense",
    subType: null,
    isVatAccount: false,
    vatType: null,
    isSystemAccount: true,
  },
];

export function createDefaultAccountsForCompany(
  companyId: string
): Omit<InsertAccount, "id" | "createdAt">[] {
  return defaultChartOfAccounts.map((account) => ({
    companyId,
    code: account.code,
    nameEn: account.nameEn,
    nameAr: account.nameAr,
    description: account.description,
    type: account.type,
    subType: account.subType,
    isVatAccount: account.isVatAccount,
    vatType: account.vatType,
    isSystemAccount: account.isSystemAccount,
    isActive: true,
    isArchived: false,
  }));
}
